### ISSUE TITLE
docpad run crashes while rendering foundation.css.scss

### ISSUE THREAD

**Issue by saberone** [axyz/zurb-foundation.docpad#2]
I'm checking out your git project for DocPad + zurb, and unfortunately I'm not able to get it to work. I have an up to date node (node.js 0.10.3) installation and the latest DocPad (docpad@6.30). Sass version is : Sass 3.2.7 (Media Mark).  I'm on OSX.

When I do a "docpad run" from the commandline I get the following message:

```
info: Welcome to DocPad v6.30.2
info: Plugins: cleanurls, coffeescript, eco, jade, livereload, marked, partials, related, sass, stylus, text
info: Environment: development
info: DocPad listening to http://localhost:9778/ on directory /Users/saber/Dev/zurb-foundation.docpad/out
info: LiveReload listening to new socket on channel /docpad-livereload with log level 1
info: Generating...
warning: Something went wrong while rendering: /Users/saber/Dev/zurb-foundation.docpad/src/documents/styles/foundation.css.scss
error: Something went wrong with the action
error: An error occured:
Error: exited with a non-zero status code
    at ChildProcess.<anonymous> (/Users/saber/Dev/zurb-foundation.docpad/node_modules/docpad-plugin-sass/node_modules/bal-util/out/lib/modules.js:114:17)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:754:12)
```

**Comment by thetechnaddict** [comment]
Same issue here

**Comment by freality** [comment]
I had the same issue. This skeleton is based on Foundation 3.x. Foundation 4.x (current) does not have `foundation/common/ratios`. I'm guessing ratios deals with typography, which Foundation removed in 4.x. commenting out `@import "foundation/common/ratios";` in src/files/vendor/zurb-foundation/sass/_settings.scss will allow docpad to compile and work with (seemingly) no issue.

**Comment by thetechnaddict** [comment]
Thanks frealty; duly commented, but now get this...

 Something went wrong while rendering: Sites/zurb-foundation.docpad/src/documents/styles/foundation.css.scss
error: Something went wrong with the action
error: An error occured: 
Error: exited with a non-zero status code
    at ChildProcess.<anonymous> (Sites/zurb-foundation.docpad/node_modules/docpad-plugin-sass/node_modules/bal-util/out/lib/modules.js:117:17)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:754:12)

**Comment by axyz** [comment]
sorry for the long wait... I'm now building a foundation 4.3.2 branch and i'll merge it onto master as soon i'll resolve a little JS problem: it just do not see foundation() function, maybe is some kind of conflict with zepto or, who knows, some silly typo. I've done it more lightweight using nodesass, coffescript(quite optional) and eco (I prefer handlebars politics in separation between logic and content... but for now i'll use eco, then later i'll evaluate if it's a good idea to switch to hb.

next plans: a good min and lint and maybe a basic usage of collection (automatic menu with pages and blog post but i'd like to keep it as simple and not specific as possible)
